app = "movieratingsapp"
primary_region = "arn"

[build]
  dockerfile = "Dockerfile"

[env]
    PORT = "5000"

[http_service]
    internal_port = 5000
    force_https = true
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 1
    processes = ["app"]